import streamlit as st


def initial_session_defaults():
    defaults = {
        "reps": 0,
        "target_sets": 0,
        "reps_per_set": 0,
        "sets_completed": 0,
        "current_set_reps": 0,
        "workout_complete": False,
        "last_notified_sets_completed": 0,
        "last_notified_workout_complete": False,
        "last_saved_sets_completed": 0,
        "set_cycle_started_at": 0.0,
        "last_exercise_type": "Squats",
        "form_score": 0,
        "form_score_total": 0,
        "form_score_samples": 0,
        "average_form_score": 0,
        "session_summary": "",
        "summary_generated": False,
        "audio_to_play": None,
        "coach_feedback": "",
        "audio_played": True,
        "audio_pause_until": 0.0,
        "workout_started_at": 0.0,
        "show_pose_overlay": False,
        "debug_mode": False,
        "camera_status": "Camera loading",
        "camera_state": "idle",
        "workout_state": "idle",
        "camera_quality": "Standard",
        "pose_model_profile": "Accuracy",
        "camera_quality_used": "Standard",
        "camera_last_error": "",
        "camera_processor_class": "N/A",
        "webrtc_key_used": "",
        "selected_exercise_locked": "",
        "last_frame_timestamp": 0.0,
        "camera_fps_estimate": 0.0,
        "last_ui_metrics_update": 0.0,
        "last_form_score_update": 0.0,
        "last_db_write": 0.0,
        "last_voice_feedback": 0.0,
        "landmark_confidence": 0.0,
        "camera_guidance": "Allow camera permission in your browser. Make sure your full body is visible.",
        "processing_status": "waiting",
        "detector_stage": "setup",
        "frame_error": "",
        "detector_issue": None,
        "is_valid_rep": False,
        "detector_debug": {},
        "detected_exercise": "Unknown",
        "exercise_confidence": 0.0,
        "pose_visibility_score": 0.0,
        "detector_name": "Unavailable",
        "pose_visibility": 0.0,
        "active_detector_exercise": "Squats",
        "app_mode": "Solo Workout",
        "show_debug_overlay": False,
        "input_fps": 0.0,
        "processed_fps": 0.0,
        "frame_count": 0,
        "average_processing_ms": 0.0,
        "skipped_frames": 0,
        "last_error": "",
        "last_major_issue_voice_at": 0.0,

        # Workout plan (set before starting)
        "workout_started": False,
        "plan_exercise": "Squats",
        "plan_sets": 3,
        "plan_reps": 10,

        # Common Angles
        "knee_angle": 0,
        "back_angle": 0,
        "elbow_angle": 0,

        # Status fields
        "depth_status": "N/A",
        "body_alignment": "N/A",
        "hip_status": "N/A",
        "hold_seconds": 0,
    }

    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value
